# Dependencies

gems:
  - jekyll-redirect-from

markdown:         kramdown

kramdown:
    entity_output: as_input

highlighter:      pygments

# Options

permalink:        pretty

# Setup

title:            TreodeDB
tagline:          'Replicated, sharded, transactional.'
description:      'A consistent and resilient database for petabytes.'
url:              http://treode.github.io
baseurl:          ''

vers:             0.3.0-SNAPSHOT
